spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123!
    url: jdbc:mysql://47.106.122.87:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
