spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123!
    url: jdbc:mysql://47.106.122.87:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

### 加上工程名,也就是url的前缀
  ### Spring boot 2.0之前配置：
  ### server.context-path=/projectname
  ### Spring boot 2.0之后配置：
  ### server.servlet.context-path=/projectname
server:
  servlet:
    context-path: /sell
